import type { CSSProperties, JSX } from 'react';
import { Handle, Position, type NodeProps, type Node } from '@xyflow/react';
import type { Device } from '../../../model/schema';
import { CARD_WIDTH, CARD_HEADER_H, PORT_ROW_H } from '../../../model/geometry';

export interface DeviceNodeData {
  device: Device;
  [key: string]: unknown;
}

export type DeviceNodeType = Node<DeviceNodeData, 'device'>;

export interface PortItem {
  id: string;
  name: string;
  label?: string | undefined;
  kind: 'interface' | 'frontPort' | 'rearPort' | 'consolePort' | 'powerPort' | 'powerOutlet';
  type?: string | undefined;
  signalClassId?: string | undefined;
}

/**
 * Extracts and flattens all materialized ports from a device in canonical order.
 * Port IDs match the IDs generated by toFlow for cable terminations.
 */
export function getDevicePorts(device: Device): PortItem[] {
  const ports: PortItem[] = [];

  if (device.interfaces) {
    for (const p of device.interfaces) {
      ports.push({
        id: p.id ?? `interface-${p.name}`,
        name: p.name,
        label: p.label,
        kind: 'interface',
        type: p.type,
        signalClassId: p.signalClassId,
      });
    }
  }

  if (device.frontPorts) {
    for (const p of device.frontPorts) {
      ports.push({
        id: p.id ?? `frontPort-${p.name}`,
        name: p.name,
        label: p.label,
        kind: 'frontPort',
        type: p.type,
        signalClassId: p.signalClassId,
      });
    }
  }

  if (device.rearPorts) {
    for (const p of device.rearPorts) {
      ports.push({
        id: p.id ?? `rearPort-${p.name}`,
        name: p.name,
        label: p.label,
        kind: 'rearPort',
        type: p.type,
        signalClassId: p.signalClassId,
      });
    }
  }

  if (device.consolePorts) {
    for (const p of device.consolePorts) {
      ports.push({
        id: p.id ?? `consolePort-${p.name}`,
        name: p.name,
        label: p.label,
        kind: 'consolePort',
        type: p.type,
        signalClassId: p.signalClassId,
      });
    }
  }

  if (device.powerPorts) {
    for (const p of device.powerPorts) {
      ports.push({
        id: p.id ?? `powerPort-${p.name}`,
        name: p.name,
        label: p.label,
        kind: 'powerPort',
        type: p.type,
        signalClassId: p.signalClassId,
      });
    }
  }

  if (device.powerOutlets) {
    for (const p of device.powerOutlets) {
      ports.push({
        id: p.id ?? `powerOutlet-${p.name}`,
        name: p.name,
        label: p.label,
        kind: 'powerOutlet',
        type: p.type,
        signalClassId: p.signalClassId,
      });
    }
  }

  return ports;
}

const cardStyle: CSSProperties = {
  boxSizing: 'border-box',
  width: `${CARD_WIDTH}px`,
  backgroundColor: 'var(--md-sys-color-surface-container, #ffffff)',
  color: 'var(--md-sys-color-on-surface, #1c1b1f)',
  border: '1px solid var(--md-sys-color-outline-variant, #cac4d0)',
  borderRadius: 'var(--md-sys-shape-corner-medium, 12px)',
  overflow: 'hidden',
  boxShadow: 'var(--md-sys-elevation-level-1, 0px 1px 3px 1px rgba(0, 0, 0, 0.15))',
  fontFamily: 'var(--md-sys-typescale-body-medium-font-family, sans-serif)',
};

const headerStyle: CSSProperties = {
  height: `${CARD_HEADER_H}px`,
  boxSizing: 'border-box',
  display: 'flex',
  alignItems: 'center',
  padding: '0 16px',
  backgroundColor: 'var(--md-sys-color-surface-container-high, #ece6f0)',
  borderBottom: '1px solid var(--md-sys-color-outline-variant, #cac4d0)',
  fontWeight: 600,
  fontSize: '14px',
};

const titleStyle: CSSProperties = {
  whiteSpace: 'nowrap',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  width: '100%',
};

const portRowStyle: CSSProperties = {
  height: `${PORT_ROW_H}px`,
  boxSizing: 'border-box',
  position: 'relative',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  padding: '0 16px',
  borderBottom: '1px solid var(--md-sys-color-outline-variant, #f0f0f0)',
  fontSize: '12px',
};

const portNameStyle: CSSProperties = {
  whiteSpace: 'nowrap',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
};

const portKindBadgeStyle: CSSProperties = {
  fontSize: '10px',
  color: 'var(--md-sys-color-on-surface-variant, #79747e)',
  marginLeft: '8px',
};

/**
 * Custom React Flow DeviceNode component.
 * Displays device name in card header and renders all ports with dual left/right handles.
 */
export function DeviceNode({ data }: NodeProps<DeviceNodeType>): JSX.Element {
  const device = data.device;
  const ports = device ? getDevicePorts(device) : [];
  const displayName = device?.name ?? device?.designation ?? device?.id ?? 'Unknown Device';

  return (
    <div className="copper-device-node" style={cardStyle} data-device-id={device?.id}>
      <header className="copper-device-header" style={headerStyle}>
        <div style={titleStyle} title={displayName}>
          {displayName}
        </div>
      </header>
      <div className="copper-device-ports">
        {ports.map((port) => {
          const portDisplayName = port.label || port.name;
          return (
            <div
              key={port.id}
              className="copper-port-row"
              style={portRowStyle}
              data-port-id={port.id}
              data-port-kind={port.kind}
            >
              <Handle
                type="target"
                position={Position.Left}
                id={port.id}
                style={{ top: '50%', transform: 'translateY(-50%)' }}
              />
              <span style={portNameStyle} title={portDisplayName}>
                {portDisplayName}
              </span>
              <span style={portKindBadgeStyle}>{port.kind}</span>
              <Handle
                type="source"
                position={Position.Right}
                id={port.id}
                style={{ top: '50%', transform: 'translateY(-50%)' }}
              />
            </div>
          );
        })}
      </div>
    </div>
  );
}
