import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';

export function IntelligenceRail() {
  const { t } = useTranslation();
  const [isOpen, setIsOpen] = useState(false);

  // Mock contextual insights based on a simulated "active object"
  const insights = [
    { id: 'IQ-1', type: 'anomaly', title: 'Cost variance detected', desc: 'Material costs are 12% higher than similar projects in this region.' },
    { id: 'IQ-2', type: 'proposal', title: 'Alternative Vendor', desc: 'Vendor V-908 has better delivery ratings and lower latency.' },
    { id: 'IQ-3', type: 'finding', title: 'Upcoming EOL', desc: '3 assets linked to this context reach End-of-Life within 90 days.' },
  ];

  return (
    <div className="fixed top-20 right-0 z-40 h-[calc(100vh-80px)]" data-testid="intelligence-rail">
      {/* Toggle Tab */}
      <button 
        data-testid="iq-rail-toggle"
        onClick={() => setIsOpen(!isOpen)}
        className={`absolute top-10 -left-10 bg-indigo-600 hover:bg-indigo-700 text-white p-2 rounded-l-md shadow-lg transition-transform ${isOpen ? 'translate-x-0' : 'translate-x-0'}`}
      >
        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
        </svg>
      </button>

      {/* Rail Panel */}
      <div className={`h-full bg-white dark:bg-slate-900 border-l border-slate-200 dark:border-slate-800 shadow-2xl transition-all duration-300 flex flex-col ${isOpen ? 'w-80 translate-x-0' : 'w-0 translate-x-full overflow-hidden border-none'}`}>
        <div className="p-4 border-b border-slate-200 dark:border-slate-800 bg-indigo-50 dark:bg-indigo-900/20">
          <h2 className="font-bold text-indigo-900 dark:text-indigo-100 flex items-center gap-2">
            <svg className="w-5 h-5 text-indigo-600 dark:text-indigo-400" fill="currentColor" viewBox="0 0 20 20"><path d="M11 3a1 1 0 10-2 0v1a1 1 0 102 0V3zM15.657 5.757a1 1 0 00-1.414-1.414l-.707.707a1 1 0 001.414 1.414l.707-.707zM18 10a1 1 0 01-1 1h-1a1 1 0 110-2h1a1 1 0 011 1zM5.05 6.464A1 1 0 106.464 5.05l-.707-.707a1 1 0 00-1.414 1.414l.707.707zM5 10a1 1 0 01-1 1H3a1 1 0 110-2h1a1 1 0 011 1zM8 16v-1h4v1a2 2 0 11-4 0zM12 14c.015-.34.208-.646.477-.859a4 4 0 10-4.954 0c.27.213.462.519.476.859h4.002z"></path></svg>
            {t('shell.iq.title', 'Intelligence Rail')}
          </h2>
          <p className="text-xs text-indigo-700 dark:text-indigo-300 mt-1">
            {t('shell.iq.subtitle', 'Contextual insights for the active stage object.')}
          </p>
        </div>
        
        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          {insights.map(item => (
            <div key={item.id} className="p-3 bg-slate-50 dark:bg-slate-800/50 rounded-lg border border-slate-200 dark:border-slate-700/60">
              <div className="flex items-center gap-2 mb-2">
                <span className={`text-[10px] uppercase font-bold px-2 py-0.5 rounded tracking-wider ${
                  item.type === 'anomaly' ? 'bg-rose-100 text-rose-700 dark:bg-rose-900/40 dark:text-rose-400' :
                  item.type === 'proposal' ? 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-400' :
                  'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-400'
                }`}>
                  {item.type}
                </span>
              </div>
              <h3 className="font-semibold text-slate-800 dark:text-slate-200 text-sm mb-1">{item.title}</h3>
              <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
        
        <div className="p-3 border-t border-slate-200 dark:border-slate-800 text-xs text-center text-slate-400">
          {t('shell.iq.footer', 'Insights generated by Copper AI')}
        </div>
      </div>
    </div>
  );
}
