import { SearchItem } from "./types";

export function getDefaultCommands(callbacks?: {
  onNavigate?: (path: string) => void;
  onExportDxf?: () => void;
  onToggleCustomerView?: () => void;
  onToggleAsOf?: () => void;
}): SearchItem[] {
  return [
    // Action commands
    {
      id: "action-new-quote",
      type: "ACTION",
      title: "New Quote",
      subtitle: "Create a new commercial quote",
      keywords: ["quote", "commercial", "new", "proposal", "sales"],
      category: "action",
      action: () => callbacks?.onNavigate?.("/commerce"),
      url: "/commerce",
    },
    {
      id: "action-go-room",
      type: "ACTION",
      title: "Go to Room",
      subtitle: "Navigate spatial tree & functional locations",
      keywords: ["room", "spatial", "location", "go", "navigate"],
      category: "action",
      action: () => callbacks?.onNavigate?.("/rooms"),
      url: "/rooms",
    },
    {
      id: "action-open-canvas",
      type: "ACTION",
      title: "Open Canvas",
      subtitle: "Schematic block diagram & wiring",
      keywords: ["canvas", "schematic", "wiring", "design", "editor"],
      category: "action",
      action: () => callbacks?.onNavigate?.("/design/canvas"),
      url: "/design/canvas",
    },
    {
      id: "action-open-rack",
      type: "ACTION",
      title: "Open Rack Elevation",
      subtitle: "Rack unit layout & equipment elevations",
      keywords: ["rack", "elevation", "equipment", "uHeight", "design"],
      category: "action",
      action: () => callbacks?.onNavigate?.("/design/rack"),
      url: "/design/rack",
    },
    {
      id: "action-open-schedule",
      type: "ACTION",
      title: "Open Cable Schedule",
      subtitle: "Cable run lengths, terminations, and wire schedule",
      keywords: ["cable", "schedule", "wire", "pull list", "design"],
      category: "action",
      action: () => callbacks?.onNavigate?.("/design/schedule"),
      url: "/design/schedule",
    },
    {
      id: "action-open-3d",
      type: "ACTION",
      title: "Open 3D Scene",
      subtitle: "3D acoustic simulation & spatial layout",
      keywords: ["3d", "scene", "acoustic", "spatial", "design"],
      category: "action",
      action: () => callbacks?.onNavigate?.("/design/3d"),
      url: "/design/3d",
    },
    {
      id: "action-export-dxf",
      type: "ACTION",
      title: "Export DXF",
      subtitle: "Export canvas schematic to AutoCAD DXF format",
      keywords: ["export", "dxf", "autocad", "download", "cad"],
      category: "action",
      action: () => callbacks?.onExportDxf?.(),
    },
    {
      id: "action-toggle-customer-view",
      type: "ACTION",
      title: "Toggle Customer View",
      subtitle: "Redact costs, margins, and internal notes",
      keywords: ["customer", "view", "mask", "privacy", "hide margins"],
      category: "action",
      action: () => callbacks?.onToggleCustomerView?.(),
    },
    {
      id: "action-toggle-as-of",
      type: "ACTION",
      title: "Toggle As-Of Mode",
      subtitle: "Time-travel to past snapshot state",
      keywords: ["as-of", "as of", "time travel", "historical", "snapshot"],
      category: "action",
      action: () => callbacks?.onToggleAsOf?.(),
    },

    // Navigation groups
    {
      id: "nav-now",
      type: "NAV",
      title: "Now",
      subtitle: "Operator inbox, active tasks, alerts, SLA clocks",
      keywords: ["now", "inbox", "tasks", "alerts", "sla"],
      category: "navigation",
      action: () => callbacks?.onNavigate?.("/now"),
      url: "/now",
    },
    {
      id: "nav-rooms",
      type: "NAV",
      title: "Rooms",
      subtitle: "Spatial tree, building hierarchy & floorplans",
      keywords: ["rooms", "spatial", "buildings", "floors", "estate"],
      category: "navigation",
      action: () => callbacks?.onNavigate?.("/rooms"),
      url: "/rooms",
    },
    {
      id: "nav-design",
      type: "NAV",
      title: "Design",
      subtitle: "AV CAD schematic, rack, schedule, 3D & compliance",
      keywords: ["design", "cad", "schematic", "rack", "3d", "compliance"],
      category: "navigation",
      action: () => callbacks?.onNavigate?.("/design"),
      url: "/design",
    },
    {
      id: "nav-commerce",
      type: "NAV",
      title: "Commerce",
      subtitle: "Quotes, agreements, customers & proposals",
      keywords: ["commerce", "quotes", "sales", "agreements", "customers"],
      category: "navigation",
      action: () => callbacks?.onNavigate?.("/commerce"),
      url: "/commerce",
    },
    {
      id: "nav-supply",
      type: "NAV",
      title: "Supply",
      subtitle: "Products, vendors, procurement & inventory",
      keywords: ["supply", "products", "vendors", "procurement", "inventory"],
      category: "navigation",
      action: () => callbacks?.onNavigate?.("/supply"),
      url: "/supply",
    },
    {
      id: "nav-service",
      type: "NAV",
      title: "Service",
      subtitle: "Tickets, SLA monitoring, maintenance & assets",
      keywords: ["service", "tickets", "sla", "support", "maintenance"],
      category: "navigation",
      action: () => callbacks?.onNavigate?.("/service"),
      url: "/service",
    },
    {
      id: "nav-insight",
      type: "NAV",
      title: "Insight",
      subtitle: "Telemetry, utilization, performance & reporting",
      keywords: ["insight", "telemetry", "reporting", "analytics", "stats"],
      category: "navigation",
      action: () => callbacks?.onNavigate?.("/insight"),
      url: "/insight",
    },
    {
      id: "nav-ops",
      type: "NAV",
      title: "Ops",
      subtitle: "Platform administration, tools governance & health",
      keywords: ["ops", "admin", "platform", "tools", "governance", "health"],
      category: "navigation",
      action: () => callbacks?.onNavigate?.("/ops"),
      url: "/ops",
    },
  ];
}
