import { SearchItem } from "./types";

export const FIXTURE_ENTITIES: SearchItem[] = [
  // FUNCTIONAL_LOCATION / ROOM
  {
    id: "FL-101",
    type: "FUNCTIONAL_LOCATION",
    code: "FL-101",
    title: "Auditorium Main Rack Room",
    subtitle: "Building 1, Floor 1 • 42U Enclosure Stack",
    keywords: ["auditorium", "rack", "room", "bldg1", "location"],
    category: "entity",
    url: "/rooms",
  },
  {
    id: "FL-102",
    type: "FUNCTIONAL_LOCATION",
    code: "FL-102",
    title: "Executive Boardroom A",
    subtitle: "Building 1, Floor 4 • 24-seat capacity",
    keywords: ["boardroom", "executive", "meeting", "cisco"],
    category: "entity",
    url: "/rooms",
  },
  {
    id: "FL-103",
    type: "FUNCTIONAL_LOCATION",
    code: "FL-103",
    title: "Broadcast Studio Master Control",
    subtitle: "Building 2, Floor 2 • Production Hub",
    keywords: ["studio", "broadcast", "control", "dante"],
    category: "entity",
    url: "/rooms",
  },

  // ASSET
  {
    id: "AST-201",
    type: "ASSET",
    code: "AST-201",
    title: "Netgear M4250 AV Rack Switch",
    subtitle: "FL-101 Auditorium • IP: 10.10.20.15",
    keywords: ["netgear", "switch", "rack", "poe", "network", "asset"],
    category: "entity",
    url: "/e/ASSET/AST-201",
  },
  {
    id: "AST-202",
    type: "ASSET",
    code: "AST-202",
    title: "Cisco Codec Pro Video Endpoint",
    subtitle: "FL-102 Boardroom • Firmware 11.14.2",
    keywords: ["cisco", "codec", "video", "conferencing", "asset"],
    category: "entity",
    url: "/e/ASSET/AST-202",
  },
  {
    id: "AST-203",
    type: "ASSET",
    code: "AST-203",
    title: "QSC Q-SYS Core 110f DSP Processor",
    subtitle: "FL-101 Auditorium • Dante ID: CORE-AUD-01",
    keywords: ["qsc", "qsys", "dsp", "core", "processor", "audio"],
    category: "entity",
    url: "/e/ASSET/AST-203",
  },
  {
    id: "AST-204",
    type: "ASSET",
    code: "AST-204",
    title: "Shure MXA910 Ceiling Array Microphone",
    subtitle: "FL-102 Boardroom • Dante Channel 1-8",
    keywords: ["shure", "mxa910", "mic", "ceiling", "array"],
    category: "entity",
    url: "/e/ASSET/AST-204",
  },

  // QUOTE
  {
    id: "Q-2026-001",
    type: "QUOTE",
    code: "Q-001",
    title: "Quote Q-2026-001 — Nordic HQ Rack Overhaul",
    subtitle: "Equinor ASA • NOK 1,450,000 • In Review",
    keywords: ["quote", "nordic", "rack", "overhaul", "equinor", "commerce"],
    category: "entity",
    url: "/commerce",
  },
  {
    id: "Q-2026-002",
    type: "QUOTE",
    code: "Q-002",
    title: "Quote Q-2026-002 — Boardroom AV Refresh",
    subtitle: "DNB Bank ASA • NOK 680,000 • Approved",
    keywords: ["quote", "boardroom", "refresh", "dnb", "cisco"],
    category: "entity",
    url: "/commerce",
  },

  // TICKET
  {
    id: "TCK-801",
    type: "TICKET",
    code: "T-801",
    title: "Ticket T-801 — Rack Thermal Warning & Fan Fault",
    subtitle: "FL-101 Auditorium • Severity: Blocker",
    keywords: ["ticket", "rack", "thermal", "fan", "fault", "service"],
    category: "entity",
    url: "/service",
  },
  {
    id: "TCK-802",
    type: "TICKET",
    code: "T-802",
    title: "Ticket T-802 — Cisco Touch 10 Controller Unresponsive",
    subtitle: "FL-102 Boardroom • Severity: Risk",
    keywords: ["ticket", "cisco", "touch10", "controller", "service"],
    category: "entity",
    url: "/service",
  },

  // PRODUCT
  {
    id: "PRD-501",
    type: "PRODUCT",
    code: "PRD-501",
    title: "Middle Atlantic 42U Heavy-Duty Server Rack",
    subtitle: "Enclosure with Glass Door & Integrated Fan Tray",
    keywords: ["rack", "middle atlantic", "42u", "enclosure", "product"],
    category: "entity",
    url: "/supply",
  },
  {
    id: "PRD-502",
    type: "PRODUCT",
    code: "PRD-502",
    title: "Genelec 8330A SAM Smart Active Monitor",
    subtitle: "Compact 2-way Active Studio Speaker",
    keywords: ["genelec", "speaker", "monitor", "audio", "product"],
    category: "entity",
    url: "/supply",
  },

  // VENDOR
  {
    id: "VND-301",
    type: "VENDOR",
    code: "VND-301",
    title: "Kinly Norway AS",
    subtitle: "Preferred System Integrator • Platinum Tier",
    keywords: ["kinly", "vendor", "integrator", "partner"],
    category: "entity",
    url: "/supply",
  },

  // CUSTOMER
  {
    id: "CUST-401",
    type: "CUSTOMER",
    code: "CUST-401",
    title: "Equinor ASA",
    subtitle: "Enterprise Account • Stavanger & Oslo Campuses",
    keywords: ["equinor", "customer", "enterprise", "client"],
    category: "entity",
    url: "/commerce",
  },

  // ACTIONS
  {
    id: "ACT-NEW-QUOTE",
    type: "ACTION",
    title: "New Quote",
    subtitle: "Create a new commercial quote for customer",
    keywords: ["new", "quote", "create", "proposal", "commercial"],
    category: "action",
    url: "/commerce",
  },
  {
    id: "ACT-GO-ROOM",
    type: "ACTION",
    title: "Go to Room",
    subtitle: "Navigate to spatial room and location hierarchy",
    keywords: ["go", "room", "navigate", "spatial", "functional location"],
    category: "action",
    url: "/rooms",
  },
  {
    id: "ACT-OPEN-CANVAS",
    type: "ACTION",
    title: "Open Canvas",
    subtitle: "System design schematic wiring and block editor",
    keywords: ["open", "canvas", "schematic", "wiring", "design"],
    category: "action",
    url: "/design/canvas",
  },
  {
    id: "ACT-OPEN-RACK",
    type: "ACTION",
    title: "Open Rack Elevation",
    subtitle: "U-accurate equipment rack elevation view",
    keywords: ["rack", "elevation", "equipment", "view", "open"],
    category: "action",
    url: "/design/rack",
  },
  {
    id: "ACT-OPEN-SCHEDULE",
    type: "ACTION",
    title: "Open Cable Schedule",
    subtitle: "Cable connections, lengths, and wire schedule",
    keywords: ["cable", "schedule", "wire", "connections", "open"],
    category: "action",
    url: "/design/schedule",
  },
  {
    id: "ACT-OPEN-3D",
    type: "ACTION",
    title: "Open 3D Scene",
    subtitle: "3D acoustic and spatial visualization",
    keywords: ["3d", "scene", "view", "spatial", "open"],
    category: "action",
    url: "/design/3d",
  },
  {
    id: "ACT-EXPORT-DXF",
    type: "ACTION",
    title: "Export DXF",
    subtitle: "Export current design to AutoCAD DXF format",
    keywords: ["export", "dxf", "autocad", "cad", "download"],
    category: "action",
  },
  {
    id: "ACT-TOGGLE-CUSTOMER-VIEW",
    type: "ACTION",
    title: "Toggle Customer View",
    subtitle: "Mask margins, costs, and internal notes",
    keywords: ["customer", "view", "mask", "privacy", "hide margins"],
    category: "action",
  },
  {
    id: "ACT-TOGGLE-AS-OF",
    type: "ACTION",
    title: "Toggle As-Of Mode",
    subtitle: "Time-travel to past snapshot state",
    keywords: ["as-of", "as of", "time travel", "historical", "snapshot"],
    category: "action",
  },
];
