export const PHYSICAL_LOCATIONS: Record<string, { code: string; color: string; bgColor: string }> = {
  'Mobile': { code: 'MBL', color: '#4A148C', bgColor: '#E1BEE7' },
  'Desktop': { code: 'DSK', color: '#E65100', bgColor: '#FFE0B2' },
  'In-Desk': { code: 'IND', color: '#E65100', bgColor: '#FFCC80' },
  'Under-Desk': { code: 'UND', color: '#E65100', bgColor: '#FFB74D' },
  'In-Floor': { code: 'INF', color: '#3E2723', bgColor: '#D7CCC8' },
  'On-Floor': { code: 'ONF', color: '#3E2723', bgColor: '#BCAAA4' },
  'In-Wall': { code: 'INW', color: '#1B5E20', bgColor: '#C8E6C9' },
  'On-Wall': { code: 'ONW', color: '#1B5E20', bgColor: '#A5D6A7' },
  'In-Ceiling': { code: 'INC', color: '#0D47A1', bgColor: '#BBDEFB' },
  'On-Ceiling': { code: 'ONC', color: '#0D47A1', bgColor: '#90CAF9' },
  'Above Ceiling': { code: 'ABC', color: '#0D47A1', bgColor: '#64B5F6' },
  'In-Rack': { code: 'INR', color: '#263238', bgColor: '#CFD8DC' },
  'Top of rack': { code: 'TOR', color: '#263238', bgColor: '#B0BEC5' },
  'Behind Parent Device': { code: 'BPD', color: '#F57F17', bgColor: '#FFF9C4' },
  'DIN-Rail': { code: 'DIN', color: '#212121', bgColor: '#E0E0E0' },
  'In-Furniture': { code: 'INU', color: '#BF360C', bgColor: '#FFCCBC' },
  'Under-Furniture': { code: 'UNF', color: '#BF360C', bgColor: '#FFAB91' },
  'In-Cabinet': { code: 'CAB', color: '#827717', bgColor: '#F0F4C3' },
  'Under-Cabinet': { code: 'UCB', color: '#827717', bgColor: '#E6EE9C' },
  'On-Pole': { code: 'POL', color: '#880E4F', bgColor: '#F8BBD0' },
  'On-Truss': { code: 'TRU', color: '#880E4F', bgColor: '#F48FB1' },
  'On-Cable Ladder': { code: 'OCL', color: '#004D40', bgColor: '#B2DFDB' },
  'In-Channel': { code: 'ICH', color: '#004D40', bgColor: '#80CBC4' }
};
